name: Ping Streamlit App

on:
  schedule:
    # Runs once per day at 12:00 UTC
    - cron: "0 12 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Streamlit App
        run: |
          curl -I https://fx-cross.streamlit.app
